[package]
name = "launchpad-mini-mk1"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "launchpad-mini-mk1"
path = "src/main.rs"
test = false
bench = false

[dependencies]
firmware-core = { path = "../../core", features = ["no-setup-btn", "launchpad-mini-mk1"] }
cortex-m.workspace = true
cortex-m-rt = { workspace = true, features = ["set-sp", "set-vtor", "device"] }
panic-halt = "1.0.0"
