[workspace]
members = [
  "core",
  "devices/launchpad-mini-mk3",
  "devices/launchpad-mini-mk1",
  "devices/launchpad-s",
  "devices/launchpad-mk2",
  "devices/launchpad-pro",
  "devices/launchpad-pro-mk3",
  "devices/launchpad-x",
  "xtask",
]
default-members = [
  "core",
  "devices/launchpad-mini-mk3",
  "devices/launchpad-mini-mk1",
  "devices/launchpad-s",
  "devices/launchpad-mk2",
  "devices/launchpad-pro",
  "devices/launchpad-pro-mk3",
  "devices/launchpad-x",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "1.0.0"
publish = false
license = "GPL-3.0-only"
authors = ["Anthony Hofmeister"]

[workspace.dependencies]
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-stm32 = { version = "0.6.0", features = ["defmt", "time-driver-tim4", "stm32f401re", "exti"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
debug = 0
panic = "abort"

[profile.release.package.launchpad-pro-mk3]
opt-level = 3
