[package]
name = "launchpad-s-and-mini"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "launchpad-s-and-mini"
path = "src/main.rs"
test = false
bench = false

[dependencies]
firmware-core = { path = "../../core" }
cortex-m.workspace = true
cortex-m-rt = { workspace = true, features = ["set-sp", "set-vtor", "device"] }
panic-halt = "1.0.0"
stm32-metapac = { version = "21.0.0", features = ["stm32f103c8"] }

[features]
default = ["launchpad-s"]
launchpad-s = ["firmware-core/launchpad-s", "firmware-core/no-setup-btn"]
launchpad-mini-mk1 = ["firmware-core/launchpad-mini-mk1", "firmware-core/no-setup-btn"]
