[package]
name = "firmware-core"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true

[lib]
name = "firmware_core"
path = "src/lib.rs"
doctest = false
test = false

[dependencies]
defmt.workspace = true

[features]
default = []
no-setup-btn = []
pressure-sensitive = []
rgb-color = []
launchpad-mini-mk1 = []
launchpad-mini-mk3 = []
launchpad-s = []
launchpad-mk2 = []
launchpad-pro = []
launchpad-pro-mk3 = []
launchpad-x = []
mystrix-pro = []
