# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bipa.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'bipa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbipa.proto\x12\x04\x62ipa\"y\n\x05Patch\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\x02 \x01(\t\x12#\n\x07inserts\x18\x03 \x03(\x0b\x32\x12.bipa.Patch.Insert\x1a(\n\x06Insert\x12\x10\n\x08position\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bipa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATCH']._serialized_start=20
  _globals['_PATCH']._serialized_end=141
  _globals['_PATCH_INSERT']._serialized_start=101
  _globals['_PATCH_INSERT']._serialized_end=141
# @@protoc_insertion_point(module_scope)
